GET http://localhost:8000/invoices HTTP/1.1

###

GET http://localhost:8000/accounts HTTP/1.1

###

POST http://localhost:8000/invoices HTTP/1.1
Content-Type: application/json

{
    "sender" : {"name" : "amd"},
    "receiver" : {"name" : "intel"},
    "amount" : "1234.5678",
    "due" : "2023-11-02 00:00:00",
    "issued" : "2021-02-03 00:00:00"
}

### 

POST http://localhost:8000/accounts HTTP/1.1
Content-Type: application/json

{
    "name" : "microsoft"
}